=== polisetti/SSDI/SOA_SSDI/SCA-INF/classes/xsd/DBAdapterService_table.xsd
<?xml version = '1.0' encoding = 'UTF-8'?>
<xs:schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdapterService" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdapterService" elementFormDefault="qualified" attributeFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="TeststockpricesCollection" type="TeststockpricesCollection"/>
   <xs:complexType name="TeststockpricesCollection">
      <xs:sequence>
         <xs:element name="Teststockprices" type="Teststockprices" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Teststockprices">
      <xs:sequence>
         <xs:element name="stockid" type="xs:decimal" nillable="true"/>
         <xs:element name="datetracked" type="xs:int" nillable="true"/>
         <xs:element name="timetracked" type="xs:int" nillable="true"/>
         <xs:element name="price" type="xs:decimal" minOccurs="0" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="DBAdapterServiceSelect_BindStockID_BindStartDate_BindEndDateInputParameters" type="DBAdapterServiceSelect_BindStockID_BindStartDate_BindEndDate"/>
   <xs:complexType name="DBAdapterServiceSelect_BindStockID_BindStartDate_BindEndDate">
      <xs:sequence>
         <xs:element name="BindStockID" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
         <xs:element name="BindStartDate" type="xs:int" minOccurs="1" maxOccurs="1"/>
         <xs:element name="BindEndDate" type="xs:int" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== polisetti/SSDI/SOA_SSDI/SCA-INF/classes/public_html/Transformation_1-Source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<TeststockpricesCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdapterService file:/C:/JDeveloper/mywork/SSDI%20Demo/SOA_SSDI/xsd/DBAdapterService_table.xsd" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBAdapterService">
   <Teststockprices>
      <stockid>19</stockid>
      <datetracked>-0</datetracked>
      <timetracked>-0</timetracked>
      <price>20</price>
   </Teststockprices>
   <Teststockprices>
      <stockid>21</stockid>
      <datetracked>-0</datetracked>
      <timetracked>-0</timetracked>
      <price>22</price>
   </Teststockprices>
   <Teststockprices>
      <stockid>23</stockid>
      <datetracked>-0</datetracked>
      <timetracked>-0</timetracked>
      <price>24</price>
   </Teststockprices>
</TeststockpricesCollection>
